name: rustskins
description: Gestion des skins du jeu Rust de Facepunch.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_native_splash: ^2.3.2
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  flutter_webview_plugin: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rust
      fonts:
        - asset: assets/fonts/Rust.ttf